-- Generated by Mocodo 4.2.1

CREATE TABLE Besoin (
  PRIMARY KEY (Code_besoin),
  Code_besoin VARCHAR(42) NOT NULL,
  Nom         VARCHAR(42),
  Quantite    VARCHAR(42)
);

CREATE TABLE CONTIENT (
  PRIMARY KEY (Code_besoin, Code_liste),
  Code_besoin VARCHAR(42) NOT NULL,
  Code_liste  VARCHAR(42) NOT NULL
);

CREATE TABLE Evenement (
  PRIMARY KEY (Code_evenement),
  Code_evenement   VARCHAR(42) NOT NULL,
  Nom              VARCHAR(42),
  Lieu             VARCHAR(42),
  Date             VARCHAR(42),
  Description      VARCHAR(42),
  Code_utilisateur VARCHAR(42) NOT NULL
);

CREATE TABLE Liste (
  PRIMARY KEY (Code_liste),
  Code_liste     VARCHAR(42) NOT NULL,
  Nom            VARCHAR(42),
  Code_evenement VARCHAR(42) NOT NULL
);

CREATE TABLE PARTICIPE (
  PRIMARY KEY (Code_evenement, Code_utilisateur),
  Code_evenement   VARCHAR(42) NOT NULL,
  Code_utilisateur VARCHAR(42) NOT NULL
);

CREATE TABLE Utilisateur (
  PRIMARY KEY (Code_utilisateur),
  Code_utilisateur VARCHAR(42) NOT NULL,
  Email            VARCHAR(42),
  Nom              VARCHAR(42),
  Prenom           VARCHAR(42)
);

ALTER TABLE CONTIENT ADD FOREIGN KEY (Code_liste) REFERENCES Liste (Code_liste);
ALTER TABLE CONTIENT ADD FOREIGN KEY (Code_besoin) REFERENCES Besoin (Code_besoin);

ALTER TABLE Evenement ADD FOREIGN KEY (Code_utilisateur) REFERENCES Utilisateur (Code_utilisateur);

ALTER TABLE Liste ADD FOREIGN KEY (Code_evenement) REFERENCES Evenement (Code_evenement);

ALTER TABLE PARTICIPE ADD FOREIGN KEY (Code_utilisateur) REFERENCES Utilisateur (Code_utilisateur);
ALTER TABLE PARTICIPE ADD FOREIGN KEY (Code_evenement) REFERENCES Evenement (Code_evenement);
