@endpoint=http://localhost:{{$dotenv PORT}}/api

### POST test authentification
POST {{endpoint}}/auth/login
Content-Type: application/json

{
    "email": "admin1.admin1@admin1.com",
    "password": "admin1"
}

