-- Generated by Mocodo 4.2.1

CREATE TABLE appartient (
  PRIMARY KEY (Code_utilisateur, Code_evenement, Code_article),
  Code_utilisateur VARCHAR(42) NOT NULL,
  Code_evenement   VARCHAR(42) NOT NULL,
  Code_article     VARCHAR(42) NOT NULL
);

CREATE TABLE ARTICLE (
  PRIMARY KEY (Code_article),
  Code_article VARCHAR(42) NOT NULL,
  Nom          VARCHAR(42),
  Quantite     VARCHAR(42)
);

CREATE TABLE EVENEMENT (
  PRIMARY KEY (Code_evenement),
  Code_evenement   VARCHAR(42) NOT NULL,
  Nom              VARCHAR(42),
  Lieu             VARCHAR(42),
  Date             VARCHAR(42),
  Description      VARCHAR(42),
  Code_utilisateur VARCHAR(42) NOT NULL
);

CREATE TABLE UTILISATEUR (
  PRIMARY KEY (Code_utilisateur),
  Code_utilisateur VARCHAR(42) NOT NULL,
  Nom              VARCHAR(42),
  Prenom           VARCHAR(42),
  email            VARCHAR(42)
);

ALTER TABLE appartient ADD FOREIGN KEY (Code_article) REFERENCES ARTICLE (Code_article);
ALTER TABLE appartient ADD FOREIGN KEY (Code_evenement) REFERENCES EVENEMENT (Code_evenement);
ALTER TABLE appartient ADD FOREIGN KEY (Code_utilisateur) REFERENCES UTILISATEUR (Code_utilisateur);

ALTER TABLE EVENEMENT ADD FOREIGN KEY (Code_utilisateur) REFERENCES UTILISATEUR (Code_utilisateur);
