@endpoint=http://localhost:{{$dotenv PORT}}/api


### GET BAD récuperation d'un evenement mauvais id
GET {{endpoint}}/event/1h
Authorization: Bearer {{$dotenv TOKEN}}

### GET BAD récuperation d'un evenement qui n'existe pas
GET {{endpoint}}/event/11
Authorization: Bearer {{$dotenv TOKEN}}

### PUT BAD creation d'un evenement manque des champs
PUT  {{endpoint}}/event
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{

}

### PUT BAD creation d'un evenement avec mauvaise date
PUT  {{endpoint}}/event
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "name": "test",
    "place": "test",
    "date": "21-12-12",
    "description": "test",
    "authorId": 1
}

### PATCH BAD modification d'un evenement avec aucun champs
PATCH  {{endpoint}}/event/1
Content-Type: application/json
Authorization : Bearer {{$dotenv TOKEN}}

{

}

### PATCH BAD modification d'un evenement qui n'existe pas
PATCH  {{endpoint}}/event/100
Content-Type: application/json
Authorization : Bearer {{$dotenv TOKEN}}


{
    "name": "test"
}

### DELETE BAD suppression d'un evenement qui n'existe pas
DELETE {{endpoint}}/event/100
Authorization : Bearer {{$dotenv TOKEN}}


