@endpoint=http://localhost:{{$dotenv PORT}}/api


### GET BAD récuperation d'un user mauvais id
GET {{endpoint}}/user/hh
Authorization: Bearer {{$dotenv TOKEN}}

### GET BAD récuperation d'un user qui n'existe pas
GET {{endpoint}}/user/11
Authorization: Bearer {{$dotenv TOKEN}}

### PUT BAD creation d'un user manque des champs
PUT  {{endpoint}}/user
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{

}

### PUT BAD creation d'un user avec un mdp différent de la confirmation
PUT  {{endpoint}}/user
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "firstname": "test",
    "lastname": "test",
    "email": "test.test@test.com",
    "password": "test",
    "confirmPassword": "test1"
}

### PUT BAD creation d'un user avec un email déjà existant
PUT  {{endpoint}}/user
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "firstname": "test",
    "lastname": "test",
    "email": "admin.admin@admin.com",
    "password": "test",
    "confirmPassword": "test"
}

### PATCH BAD modification d'un user avec aucun champs
PATCH  {{endpoint}}/user/1
Content-Type: application/json
Authorization : Bearer {{$dotenv TOKEN}}

{

}

### PATCH BAD modification d'un user qui n'existe pas
PATCH  {{endpoint}}/user/100
Content-Type: application/json
Authorization : Bearer {{$dotenv TOKEN}}


{
    "firstname": "test"
}

### DELETE BAD suppression d'un user qui n'existe pas
DELETE {{endpoint}}/user/100
Authorization : Bearer {{$dotenv TOKEN}}


