@endpoint=http://localhost:{{$dotenv PORT}}/api

### GET recuperation de tous les utilisateurs
GET {{endpoint}}/user
Authorization: Bearer {{$dotenv TOKEN2}}


### GET récupération d'un utilisateur avec token
GET {{endpoint}}/user/1
Authorization: Bearer {{$dotenv TOKEN}}


### PUT creation d'un utilisateur
PUT {{endpoint}}/user
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "firstname": "test",
    "lastname": "test",
    "email": "test@test.test",
    "password": "testtest",
    "confirmPassword": "testtest"
}

### PATCH modification d'un utilisateur
PATCH {{endpoint}}/user/45
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "firstname": "test2",
    "lastname": "test2",
    "email": "test2@test2.test",
    "password": "testtest2",
    "confirmPassword": "testtest2"
}

### DELETE suppression d'un utilisateur
DELETE {{endpoint}}/user/4