@endpoint=http://localhost:{{$dotenv PORT}}/api

### POST connexion
POST {{endpoint}}/auth/login
Content-Type: application/json

{
    "email": "admin1.admin1@admin1.com",
    "password": "admin1"
}

### GET recuperation de tous les utilisateurs
GET {{endpoint}}/user
Authorization: Bearer {{$dotenv TOKEN}}


### GET récupération d'un utilisateur avec token
GET {{endpoint}}/user/1
Authorization: Bearer {{$dotenv TOKEN}}


### PUT creation d'un utilisateur
PUT {{endpoint}}/user
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "firstname": "test",
    "lastname": "test",
    "email": "test@test.test",
    "password": "testtest",
    "confirmPassword": "testtest"
}

### PATCH modification d'un utilisateur
PATCH {{endpoint}}/user/9
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "firstname": "test2",
    "lastname": "test2",
    "email": "test2@test3.test",
    "password": "testtest4",
    "confirmPassword": "testtest4"
}

### DELETE suppression d'un utilisateur
DELETE {{endpoint}}/user/7
Authorization: Bearer {{$dotenv TOKEN}}